### PR TITLE
Add limitation on foreign key action support in schema conversion

### PR DESCRIPTION
**Pull request by gunjan-juyal**
Adds limitation on foreign key action support (such as DELETE CASCADE) in schema conversion to the README.

ON DELETE CASCADE support is expected to roll out soon in Spanner for both GoogleSQL and PostgreSQL dialects. So far, the only (and default) action supported is "NO ACTION". Since HarbourBridge does not support foreign key referential actions yet, the README is being updated.

### CODE REVIEW

**Comment by gunjan-juyal** [comment]
This PR is created in a Draft mode since the DELETE CASCADE foreign key Action is not yet supported in Spanner. This would be marked as "Ready for Review" once it is available.

**Review by manitgupta — APPROVED** [review]
We will be merged once @gunjan-juyal confirms that the feature is GA

**Comment by gunjan-juyal** [comment]
@manitgupta Please note that the feature is visible, hence these changes can be merged to mainline (master) now

**Comment by gunjan-juyal** [comment]
@manitgupta Checking in on when we can merge this PR, since the feature has been GA since over a week now

**Comment by manitgupta** [comment]
Merged!

**Pull request merged**
