### PR TITLE
feat(frontend): add postgres support for dataproc migration

### PR DESCRIPTION
**Pull request by forksumit**
This PR includes ui changes to show dataproc migration mode dropdown for source: Postgres.

Modify source type checks to allow postgres source as well (along with MySQL) in prepare-migration component 
[`SourceDbNames.MySQL` || `SourceDbNames.Postgres`]

### CODE REVIEW

**Comment by forksumit** [comment]
To be merged after: PR https://github.com/GoogleCloudPlatform/spanner-migration-tool/pull/594

**Review by bharadwaj-aditya — CHANGES_REQUESTED** [review]
LGTM

**Review by shreyakhajanchi — COMMENTED** [review]
LGTM

**Review by bharadwaj-aditya — APPROVED** [review]
LGTM

**Pull request merged**
